let products = [
    { 
        "id": 1001,
        "title": "Football - Dubai",
        "price": 2000,
        "image": "images/football.jpeg",
        "stock": 22,
        "availableSlots": 22,
        "showProduct": true,
    },
    { 
        "id": 1002,
        "title": "Badminton - Dubai",
        "price": 1000,
        "image": "images/badminton.jpg",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1003,
        "title": "Basketball - Dubai",
        "price": 2000,
        "image": "images/basketball.jpeg",
        "stock": 20,
        "availableSlots": 20,
        "showProduct": true,
    },
    { 
        "id": 1004,
        "title": "Chess - Dubai",
        "price": 800,
        "image": "images/chess.png",
        "stock": 10,
        "availableSlots": 10,
        "showProduct": true,
    },
    { 
        "id": 1005,
        "title": "Cricket - Dubai",
        "price": 2000,
        "image": "images/cricket.png",
        "stock": 22,
        "availableSlots": 22,
        "showProduct": true,
    },
    { 
        "id": 1006,
        "title": "Hockey - Dubai",
        "price": 1000,
        "image": "images/hockey.png",
        "stock": 20,
        "availableSlots": 20,
        "showProduct": true,
    },
    { 
        "id": 1007,
        "title": "Horse Riding - Dubai",
        "price": 5000,
        "image": "images/horse_riding.png",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1008,
        "title": "Swimming - Dubai",
        "price": 2000,
        "image": "images/swimming.jpg",
        "stock": 10,
        "availableSlots": 10,
        "showProduct": true,
    },
    { 
        "id": 1009,
        "title": "Table Tennis - Dubai",
        "price": 1000,
        "image": "images/table-tennis.png",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1010,
        "title": "Volleyball - Dubai",
        "price": 2000,
        "image": "images/volleyball.png",
        "stock": 12,
        "availableSlots": 12,
        "showProduct": true,
    },
    { 
        "id": 1011,
        "title": "Football - Abu Dhabi",
        "price": 2000,
        "image": "images/football.jpeg",
        "stock": 22,
        "availableSlots": 22,
        "showProduct": true,
    },
    { 
        "id": 1012,
        "title": "Badminton - Abu Dhabi",
        "price": 1000,
        "image": "images/badminton.jpg",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1013,
        "title": "Basketball - Abu Dhabi",
        "price": 2000,
        "image": "images/basketball.jpeg",
        "stock": 20,
        "availableSlots": 20,
        "showProduct": true,
    },
    { 
        "id": 1014,
        "title": "Chess - Abu Dhabi",
        "price": 800,
        "image": "images/chess.png",
        "stock": 10,
        "availableSlots": 10,
        "showProduct": true,
    },
    { 
        "id": 1015,
        "title": "Cricket - Abu Dhabi",
        "price": 2000,
        "image": "images/cricket.png",
        "stock": 22,
        "availableSlots": 22,
        "showProduct": true,
    },
    { 
        "id": 1016,
        "title": "Hockey - Abu Dhabi",
        "price": 1000,
        "image": "images/hockey.png",
        "stock": 20,
        "availableSlots": 20,
        "showProduct": true,
    },
    { 
        "id": 1017,
        "title": "Horse Riding - Abu Dhabi",
        "price": 5000,
        "image": "images/horse_riding.png",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1018,
        "title": "Swimming - Abu Dhabi",
        "price": 2000,
        "image": "images/swimming.jpg",
        "stock": 10,
        "availableSlots": 10,
        "showProduct": true,
    },
    { 
        "id": 1019,
        "title": "Table Tennis - Abu Dhabi",
        "price": 1000,
        "image": "images/table-tennis.png",
        "stock": 8,
        "availableSlots": 8,
        "showProduct": true,
    },
    { 
        "id": 1020,
        "title": "Volleyball - Abu Dhabi",
        "price": 2000,
        "image": "images/volleyball.png",
        "stock": 12,
        "availableSlots": 12,
        "showProduct": true,
    }
];